name: Run automated tests

on:
  push:
    branches: [ fix_action2 ]  # TODO master
  
jobs:
  run-tests:
 
    runs-on: ubuntu-20.04
    
    container:
      image: lubo1994/pv-drone-inspect:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deepdiff==5.7.0 hypothesis[numpy]==6.31.6 flake8==4.0.1 coverage==6.2 gdown==4.2.0
          
      - run: mkdir -p /pvextractor/extractor/segmentation/Mask_RCNN/logs/pv_modules20210521T1611/
        
      - name: Download Mask R-CNN weights from Google Drive
        run: gdown https://drive.google.com/uc?id=1DzZNU9NBmHg_SFoazbHnz3q-y0jN1BIS -O /pvextractor/extractor/segmentation/Mask_RCNN/logs/pv_modules20210521T1611/mask_rcnn_pv_modules_0120.h5
          
      #- name: Lint with flake8
      #  run: |
      #    # stop if there are syntax errors or undefined names
      #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #    # exit-zero treats all errors as warnings, the GitHub editor is 127 chars wide
      #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
      - name: Test with unittest
        run: |
          python -m unittest tests/integration/test_segmentation.py
        #run: |
        #  python -m unittest tests/**/test_*.py
          
      #- name: Test coverage analysis
      #  run: |
      #    coverage run --source=. --branch -m unittest tests/**/test_*.py
      #    coverage report -m
      #    # create html coverage report in htmlcov
      #    coverage html
